CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  name CHARACTER VARYING  NOT NULL,
  github_id BIGINT NOT NULL,
  github_login CHARACTER VARYING NOT NULL,
  url CHARACTER VARYING NOT NULL,
  html_url CHARACTER VARYING NOT NULL,
  repos_url CHARACTER VARYING NOT NULL,
  access_token CHARACTER VARYING NOT NULL
);

CREATE UNIQUE INDEX users_github_id ON users (github_id);
