logging:
  level:
    root: info
    org:
      springframework:
        web: debug
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  config:
    import:
      - "secrets.yaml"