logging:
  level:
    root: info
    # Print mappings
    # _org.springframework.web.servlet.HandlerMapping.Mappings: debug
    org:
      springframework:
        web: debug
spring:
  config:
    import:
      - "secrets.yaml"